name: Site Gen

on:
  push:
    branches: [ $default-branch, "github-actions" ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build-blog:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get `site-gen`
      run: |
        wget https://github.com/littlebenlittle/site-gen/releases/download/actions-test-00/site-gen
        chmod +x ./site-gen
    - name: Build dev blog
      run: |
        cd dev-blog
        RUST_LOG=debug ../site-gen
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dev-blog/_site
          
  deploy-blog:
    # Add a dependency to the build job
    needs: build-blog

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
